### ISSUE TITLE
[Bug] crash on npm install 

### ISSUE THREAD

**Issue by ldgonzalez26** [creativetimofficial/ct-argon-design-system-pro-react#5]
### Version
1.0.1
### Reproduction link
https://jsbin.com/?html,output
### Operating System
MacOs
### Device
MACBOOK PRO 
### Browser & Version
NO-NEED
### Steps to reproduce
1.- download the project
2.- run npm install
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0 || ^17.0.0" from react-datetime@3.1.1
### What is expected?
The project should build properly 
### What is actually happening?
bunch of errors ( I solved that one by updating that dependency but it keep feeling on every dependency ) 

---
### Solution
I do think this shouldnt happen on the latest version of the product however when I download it i can only have the 1.0.1 not 1.2.1 as the changelog suggest

**Comment by sajadevo** [comment]
This issue is fixed on v1.0.2
